#!/usr/bin/env tsx
/**
 * Console build — the standalone page, as a single file.
 *
 * `packages/console/` holds the only human-facing UI of the project: a real web
 * page (workers, chat, snapshots, plugin install, diagnostics). Not a popup, not
 * an injected overlay. This script bundles it into one self-contained HTML
 * document and hands it to the two places that serve it:
 *
 *   build/console/console.html                     ← inspectable artifact (+ .js/.css)
 *   packages/runtime/src/generated/console-html.ts ← `browsermind serve` answers `/`
 *                                                     with this string, no static dir
 *
 * Rules:
 *   - output is inlined (no external `src`/`href`), so the page also works when
 *     opened from inside the extension or straight from disk;
 *   - `</script` is escaped so a fenced code block in a bundled string can never
 *     close the inline <script> element;
 *   - builds are deterministic (no timestamps), so CI can diff the artifact.
 *
 * Usage:
 *   npm run console:build            # one-off (also runs from `npm install`)
 *   npm run console:watch            # `tsx watch` — rebuilds on every change
 *   npx tsx scripts/build-console.ts --out ./dist/console --minify false
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createHash } from 'node:crypto';
import * as esbuild from 'esbuild';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const consoleDir = path.join(root, 'packages', 'console');

export interface BuildConsoleOptions {
  /** Output folder. Default `<repo>/build/console`. */
  out?: string;
  /** Also write the generated module the runtime serves. Default true. */
  injectRuntime?: boolean;
  minify?: boolean;
  sourcemap?: boolean;
  quiet?: boolean;
}

export interface BuildConsoleResult {
  outDir: string;
  htmlPath: string;
  bytes: number;
  sha256: string;
  /** Absolute path of the generated runtime module, when written. */
  generatedModule?: string;
}

const STYLE_TAG = '<link rel="stylesheet" href="./styles.css" />';
const SCRIPT_TAG = '<script type="module" src="./src/main.ts"></script>';

/**
 * Inline content must never be able to terminate its own element, and the
 * replacement must be literal: bundled code contains `$&`, `` $` `` and `$'` all
 * the time, which `String.replace` would otherwise expand. Hence the functions.
 */
function protect(tag: string, content: string): string {
  const closing = `</${tag}`;
  const escaped = `<\/${tag}`;
  let output = '';
  let cursor = 0;
  for (;;) {
    const index = content.toLowerCase().indexOf(closing, cursor);
    if (index === -1) break;
    output += content.slice(cursor, index) + escaped;
    cursor = index + closing.length;
  }
  return `${output}${content.slice(cursor)}`.replace(/<!--/g, () => '<\\!--');
}

export async function buildConsolePage(options: BuildConsoleOptions = {}): Promise<BuildConsoleResult> {
  const outDir = path.resolve(root, options.out ?? path.join('build', 'console'));
  const html = await readFile(path.join(consoleDir, 'index.html'), 'utf8');
  const css = await readFile(path.join(consoleDir, 'styles.css'), 'utf8');

  const result = await esbuild.build({
    entryPoints: [path.join(consoleDir, 'src', 'main.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    minify: options.minify ?? true,
    sourcemap: options.sourcemap ?? false,
    legalComments: 'none',
    write: false,
    logLevel: 'silent',
  });
  const js = result.outputFiles[0]?.text ?? '';

  if (!html.includes(STYLE_TAG) || !html.includes(SCRIPT_TAG)) {
    throw new Error(
      'console: index.html must keep the inlining markers ' +
        `\`${STYLE_TAG}\` and \`${SCRIPT_TAG}\` — scripts/build-console.ts replaces them.`,
    );
  }

  // Function replacers only — a `$` in the bundle is not a replacement pattern.
  const page = html
    .replace(STYLE_TAG, () => `<style>\n${protect('style', css)}\n</style>`)
    .replace(SCRIPT_TAG, () => `<script>\n${protect('script', js)}\n</script>`);

  await mkdir(outDir, { recursive: true });
  await Promise.all([
    writeFile(path.join(outDir, 'console.html'), page, 'utf8'),
    writeFile(path.join(outDir, 'console.js'), js, 'utf8'),
    writeFile(path.join(outDir, 'console.css'), css, 'utf8'),
  ]);

  const generatedModule = options.injectRuntime === false ? undefined : path.join(root, 'packages', 'runtime', 'src', 'generated', 'console-html.ts');
  if (generatedModule) {
    await mkdir(path.dirname(generatedModule), { recursive: true });
    await writeFile(
      generatedModule,
      `/**
 * AUTO-GENERATED by scripts/build-console.ts — do not edit by hand.
 *
 * The standalone console page, inlined into one self-contained HTML document so
 * \`browsermind serve\` can answer \`/\` (and \`/console\`) with a real page instead of an
 * extension popup. Rebuild after touching anything in \`packages/console\`:
 *
 *   npm run console:build
 */
export const CONSOLE_HTML = ${JSON.stringify(page)};
`,
      'utf8',
    );
  }

  const bytes = Buffer.byteLength(page, 'utf8');
  const built: BuildConsoleResult = {
    outDir,
    htmlPath: path.join(outDir, 'console.html'),
    bytes,
    sha256: createHash('sha256').update(page).digest('hex'),
    generatedModule,
  };
  if (options.quiet !== true) {
    console.log(
      `[console:build] ${(bytes / 1024).toFixed(1)} kB → ${path.relative(root, built.htmlPath)}` +
        (generatedModule ? ` + ${path.relative(root, generatedModule)}` : ''),
    );
  }
  return built;
}

/* ----------------------------------- cli ----------------------------------- */

function parseFlags(argv: string[]): Record<string, string | boolean> {
  const flags: Record<string, string | boolean> = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index]!;
    if (!token.startsWith('-')) continue;
    const key = token.replace(/^--?/, '');
    const next = argv[index + 1];
    if (next !== undefined && !next.startsWith('-')) {
      flags[key] = next;
      index += 1;
    } else flags[key] = true;
  }
  return flags;
}

const invokedDirectly = process.argv[1] ? import.meta.url === pathToFileURL(process.argv[1]).href : false;

if (invokedDirectly) {
  const flags = parseFlags(process.argv.slice(2));
  const options: BuildConsoleOptions = {
    out: typeof flags.out === 'string' ? flags.out : undefined,
    minify: flags.minify !== false && flags.minify !== 'false',
    sourcemap: flags.sourcemap === true || flags.sourcemap === 'true',
    injectRuntime: flags['no-inject'] !== true,
  };
  try {
    if (!existsSync(consoleDir)) throw new Error(`missing ${consoleDir}`);
    await buildConsolePage(options);
  } catch (error) {
    console.error('[console:build] failed:', error);
    process.exitCode = 1;
  }
}
